name: Build and Push Docker Image

on:
  push:
    branches:
      - app  # Trigger on push to main branch; adjust as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./app  # Path to your Dockerfile
        file: ./app/Dockerfile
        push: true
        tags: cdaprod/minio-weaviate-langchain:latest
